# Generated by Django 5.2.9 on 2026-02-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="probability",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
